# Generated by Django 4.0.2 on 2022-02-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_counting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
